#!C:\Users\91780\AppData\Local\Programs\Python\Python37-32\Python.exe
print('content-type:text/html\r\n\n')
print('<html>')
print('<head>')
print('</head>')
print('<body style="margin:0;">')
print('<form method="post">')
print('<div style="background-image:url(image1.jpg);width:100%;height:15%;font-size:50;font-color:white"><center>NATIONAL INSTITUTE OF TECHNOLOGY HAMIRPUR</center></div>')
print('<div style="background-image:url(image12.jpg);width:100%;height:85%;font-size:30;">')
print('<div style="width:85%;height:100%;font-size:30;float:right;">')
print('<div style="width:80%;height:100%;font-size:30;float:left;">')
print('<p align="center" style="font-size:30;color:white;margin-left:-4em;">')
print("<b>Lab Name </b>  : <input type='text' name='LN'>")
print('<br>')
print("<b>Lab Code</b> : <input type='text' name='LC'>")
print('<br>')
print("<b>Teacher Name  </b>  : <input type='text' name='TN'>")
print('<br>')
print("<b>Branch </b>  : <input type='text' name='Branch'>")
print('<br>')
print('<center><input type="submit" name="submit" value="SUBMIT" style="font-size:0.5em;color:blue;display:block;"></center>')
print('</div>')
print('</div>')
print('</div>')
print('</form></body>')
print('</html>')
from project import *
import cgi,cgitb
form=cgi.FieldStorage()
if form.getvalue("submit"):
    a=form.getvalue("LN")
    b=form.getvalue("LC")
    c=form.getvalue("TN")
    d=form.getvalue("Branch")
    addlab(a,b,c,d)
