#!C:\Users\91780\AppData\Local\Programs\Python\Python37-32\Python.exe
import webbrowser
print("Content-type:text/html\r\n\n")
print('<html>')
print('<head>')
print('<title></title>')
print('</head>')
print('<body style="background-color:white;">')
print('<div class="header">')
print('<div style="background-image:url(image1.jpg);width:100%;height:125px;font-size:45;"><br><center><b>TIMETABLE MANAGMENT</b></center></div>')
print('</div>')
print('<div style="background-image:url(image12.jpg);width:100%;height:675px;"><div><form action="project1.py" method="post"><p align="center" style="font-size:22;color:black;margin-left:-4em;"><table align="center" width="100" height="100">')
print('<tr><td align="center" style=font-size:25;color:white;><a href="http://localhost/Timetable/Add_Lab.py" target="blank"><b>Add_Lab </b></a></td></tr>')
print('<tr><td align="center" style=font-size:25;color:white;><a href="http://localhost/Timetable/Add_Teacher.py" target="blank"><b>Add_Teacher</b></a></td></tr>')
print('<tr><td align="center" style=font-size:25;color:white;><a href="http://localhost/Timetable/add_subject.py" target="blank"><b>Add_Subject</b></a></td></tr>')
print('<tr><td align="center" style=font-size:25;color:white;><a href="http://localhost/timetable/Add_room.py" target="blank"><b>Add_room</b></a></td></tr>')
print('<tr><td align="center" style=font-size:25;color:white;><a href="http://localhost/Timetable/remove_room.py" target="blank"><b>Remove_room </b></a></td></tr>')
print('<tr><td align="center" style=font-size:25;color:white;><a href="http://localhost/Timetable/Show_timetable.py" target="blank"><b>Show_Timetable</b></a></td></tr>')
print('</table>')
print('</form>')
print('</div>')
print('</body>')
print('</html>')
